Update stratis-min to clap v3 API
Convert to the v3 API (App -> Command etc.) and fix incompatibility with
the new version:

Remove the explicit lifetime parameters from get_paths_from_args(); the
Clap v3 struct ArgMatches no longer accepts a lifetime generic.

Add an explicit definition for the 'pool add-cache' subcommand. Clap v3
is more strict in parsing subcommands and arguments and panics if a
subcommand is passed to subcommand_matches() that had not previously
been defined with Command::new():

  thread 'main' panicked at '`add-cache` is not a name of a subcommand.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:1060:14
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: clap::parse::matches::arg_matches::ArgMatches::get_subcommand
               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:1171:17
     3: clap::parse::matches::arg_matches::ArgMatches::subcommand_matches
               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:1060:9
     4: stratis_min::main
               at ./src/bin/stratis-min/stratis-min.rs:228:36
     5: core::ops::function::FnOnce::call_once
               at /builddir/build/BUILD/rustc-1.60.0-src/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.