Remove repeated 'bytes' in the error message when blockdev is too small
While running tests with 'stratis pool create' I got the following error:

$ stratis pool create pequenho /dev/vdb
Execution failure caused by:
ERROR: /dev/vdb too small, minimum 1073741824 bytes bytes

This patch attemps to fix the double 'bytes' output. The result of testing
it is:

Execution failure caused by:
ERROR: /dev/vdb too small, minimum 1073741824 bytes

Signed-off-by: Jose Castillo <jcastillo@redhat.com>